### ISSUE TITLE
[BUG] PCA from prepare_phenotype_table.py has incorrect dimension

### ISSUE THREAD

**Issue by boxiangliu** [davidaknowles/leafcutter#43] opened 2017-11-04 00:14 UTC
HI @davidaknowles, 

The PCA output from prepare_phenotype_table.py has N columns, where N is the number of clusters. Instead, I think one wants M columns, where M is the number of individuals. On line 149 there is `matrix = np.transpose(matrix) # important bug fix`, which seems to be causing the problem.

**Comment by goldenflaw** [comment] 2017-11-04 00:37
Hi Bosh,

Are you sure? I'm not looking at this now, but could you make sure that
this bugfix is incorrect?

Yang

On Nov 3, 2017 7:14 PM, "Boxiang Liu" <notifications@github.com> wrote:

HI @davidaknowles <https://github.com/davidaknowles>,

The PCA output from prepare_phenotype_table.py has N columns, where N is
the number of clusters. Instead, I think one wants M columns, where M is
the number of individuals. On line 149 there is matrix =
np.transpose(matrix) # important bug fix, which seems to be causing the
problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davidaknowles/leafcutter/issues/43>, or mute the thread

**Comment by boxiangliu** [comment] 2017-11-04 03:26
@goldenflaw Unless there is a version difference in sklearn, I am quite sure. Here is an example input. Maybe try to see if you can reproduce on your machine. 
[sqtl_perind_numers.counts.gz](https://github.com/davidaknowles/leafcutter/files/1442880/sqtl_perind_numers.counts.gz)

**Comment by davidaknowles** [comment] 2017-11-05 05:03
Yeah I think you're right about this Bosh: on the example_data the PCs matrix I get is nPCs x 1605 (1605=num of quantifiable introns), whereas it should be nPCs x 10 (number of samples). Removing that transpose line gets the correct dimension. Is this the right way around for fastQTL or should it be |samples| x |PCs| ?

**Comment by goldenflaw** [comment] 2017-11-05 06:54
Interesting, someone else reported that bugfix, and I swore they were right.

**Comment by xtmgah** [comment] 2017-12-15 21:19
Hello @boxiangliu @davidaknowles @goldenflaw 

I have the same issue, So,should I simply remove this line: " matrix = np.transpose(matrix) # important bug fix" ?? I am confused. Thanks.

**Comment by xtmgah** [comment] 2017-12-15 21:24
And which is the final value for PCA calculation? can we reproduce  the PCA from "perind.counts.gz.qqnorm_chr.all"?

**Comment by goldenflaw** [comment] 2018-01-01 21:34
The bug fix has been reverted. Sorry for the delay!

**Closed by goldenflaw** 2018-01-01 21:34 UTC
